'use client';
import {useEffect,useState} from 'react';
import {cash} from '@/lib/rankme/commerce';
import {api} from './join-form';
export function ServiceAdmin({demo,profiles}:{demo:boolean;profiles:any[]}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[profile,setProfile]=useState(''),[status,setStatus]=useState('hidden'),[reason,setReason]=useState(''),[rule,setRule]=useState(''),[impact,setImpact]=useState(''),[name,setName]=useState(''),[bio,setBio]=useState(''),[removeAvatar,setRemoveAvatar]=useState(false);
 async function refresh(){try{setData(await api('admin/service'))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(!demo)void refresh()},[demo]);
 async function send(payload:unknown){if(demo){setError('Demo změny neukládá.');return}setBusy(true);setError('');try{await api('admin/service',payload);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="settings-card service-form"><h2>Odůvodněná moderace a žádosti</h2><p>Omezení profilu, odůvodnění, audit a e-mail se uloží společně. Při vyřízení odvolání napiš výsledek; pokud měníš původní omezení, nejdříve zde proveď nové rozhodnutí. Nepotvrzuj refundaci, dokud ji nepotvrdí Dodo.</p><form onSubmit={e=>{e.preventDefault();void send({action:'moderate',id:profile,status,reason,rule,impact,...(status==='edit'?{name,bio,remove_avatar:removeAvatar}:{})})}}><fieldset disabled={busy}><label>Profil<select required value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Vyber profil</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} — {p.id}</option>)}</select></label><label>Opatření<select value={status} onChange={e=>setStatus(e.target.value)}>{[['hidden','Skrýt'],['under_review','Prověřovat'],['banned','Zablokovat profil'],['deleted','Odstranit'],['active','Obnovit'],['edit','Upravit jméno nebo bio'],['ban_user','Zablokovat celý účet'],['unban_user','Odblokovat celý účet']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{status==='edit'&&<><label>Nové jméno<input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>Nové bio<textarea maxLength={1000} value={bio} onChange={e=>setBio(e.target.value)}/></label><label><input type="checkbox" checked={removeAvatar} onChange={e=>setRemoveAvatar(e.target.checked)}/>Odstranit fotografii</label></>}<label>Konkrétní důvod a zjištěné okolnosti<textarea required minLength={20} maxLength={5000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Pravidlo nebo právní důvod<input required minLength={3} maxLength={500} value={rule} onChange={e=>setRule(e.target.value)}/></label><label>Dopad na platby a dostupnost služby<textarea required minLength={10} maxLength={2000} value={impact} onChange={e=>setImpact(e.target.value)}/></label><button className="primary-button">Provést a uložit rozhodnutí</button></fieldset></form>{error&&<p role="alert" className="form-error">{error}</p>}
 {data&&<><h3>Provozní e-maily</h3><p>{data.mail_configured?'Odesílatel je nakonfigurovaný.':'Odesílatel čeká na nastavení. Fronta zůstává zachovaná.'} Čekajících / neúspěšných v tomto výpisu: {data.mail.length}.</p><button disabled={busy||!data.mail_configured} onClick={()=>send({action:'dispatch'})}>Zpracovat frontu e-mailů</button>{data.mail.map((m:any)=><p key={m.id}>{m.subject} · {m.status} · pokus {m.attempts} {m.last_error||''}</p>)}<h3>Platby Dodo</h3>{data.orders.map((o:any)=><RefundOrder key={o.id} o={o} refresh={refresh}/>)}<h3>Žádosti (posledních 100)</h3>{data.requests.map((r:any)=><RequestItem key={r.id} r={r} busy={busy} send={send}/>)}</>}
 </section>;
}
function RequestItem({r,busy,send}:{r:any;busy:boolean;send:(p:unknown)=>Promise<void>}){const [resolution,setResolution]=useState(''),[verify,setVerify]=useState(false);return <article className="settings-card"><h4>FR-S-{r.case_number} · {r.kind} · {r.status}</h4><p>{r.name} · {r.email}</p><p>Reference: {r.reference}</p><p>{r.details}</p>{r.status==='resolved'?<p>{r.resolution}</p>:<form onSubmit={e=>{e.preventDefault();void send({action:'resolve',id:r.id,resolution,verified_country:verify?r.country:null})}}><label>Výsledek a odůvodnění<textarea value={resolution} onChange={e=>setResolution(e.target.value)} minLength={20} maxLength={5000} required/></label>{r.kind==='country'&&<label><input type="checkbox" checked={verify} onChange={e=>setVerify(e.target.checked)}/>Ověřil/a jsem podklady a schvaluji zemi {r.country}. V odůvodnění uvádím použitý podklad.</label>}<button disabled={busy}>Uzavřít a připravit vyrozumění</button></form>}</article>}

function RefundOrder({o,refresh}:{o:any;refresh:()=>Promise<void>}){const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');return <article><p>{o.id} · {cash(o.amount,o.currency)} · {o.status}</p>{o.provider_payment_id&&['paid','review'].includes(o.status)&&<><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Ověřil/a jsem oprávněnost vrácení celé zbývající platby přes Dodo.</label><button disabled={!confirm||busy} onClick={async()=>{setBusy(true);try{const r=await api('admin/dodo-refund',{id:o.id,confirmed:true});setMessage(r.message);await refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Zadat refundaci v Dodo</button></>}<p role="status">{message}</p></article>}
