import {PRIVATE_RULES_VERSION} from './private-v1';

// Invitation-only, free pilot. Public and paid operation requires a new version.
export const privatePolicy={
  version:PRIVATE_RULES_VERSION,
  sections:[
    {title:'Služba a dohoda',text:'FameRiser v soukromém pilotu zdarma umožňuje vytvořit jeden creator profil, ověřit ovládané sociální účty a případně zobrazit profil v žebříčku dostupném osobám s přístupem k pilotu. Dohoda o používání pilotu vzniká vytvořením creator profilu po přijetí těchto pravidel; přihlašovací účet může vzniknout dříve po e-mailové pozvánce. Registrace, ověření i účast v žebříčku jsou bez poplatku. Platby, výběry, výhry a veřejný provoz nyní nejsou dostupné.'},
    {title:'Provozovatel a kontakt',text:'Službu provozuje Petr Suchý, IČO 87155982, Československé armády 723, Místek, 738 01 Frýdek-Místek, Česká republika. Pro podporu, reklamaci fungování služby, oznámení obsahu a právní komunikaci slouží info@fameriser.com. Podání posoudíme v přiměřené době podle jeho povahy; zákonná práva spotřebitele tím nejsou omezena.'},
    {title:'Kdo a jak může pilot používat',text:'Účet je určen osobám starším 18 let, které mají pozvánku a potvrdí svůj e-mail. Uživatel odpovídá za správnost zadaného jména, země a údajů o ovládaných sociálních účtech. Připojit lze jen účet, který skutečně ovládá nebo je oprávněn zastupovat. Ověření poskytovatelem neověřuje občanskou identitu, kvalitu obsahu ani souhlas třetích osob. Zakázáno je vydávání se za jiného, nezákonný obsah, zásahy do práv jiných, manipulace ověřením a obcházení technických omezení.'},
    {title:'Ověřené účty a FameCredit',text:'Jeden uživatel má jeden creator profil a může k němu připojit více odlišných ověřených sociálních účtů. V pilotu je připraveno ověření kanálu YouTube přes Google. Používáním této funkce souhlasíš také s podmínkami služby YouTube uvedenými na youtube.com/t/terms. Samotný odkaz, snímek obrazovky ani platba nejsou důkazem ovládání účtu. Za první připojení každé nové ověřené sociální identity se jednou připíše 1 FameCredit (FC), nejvýše 10 uvítacích FC na creator profil. Opětovné připojení další FC nepřipisuje. FC je jen nepeněžní bodová hodnota pro pořadí; není měnou ani platebním prostředkem a nelze jej vyplatit ani převést. Po odpojení účtu dříve přidělené FC zůstávají v celkovém součtu. Spornou změnu oprávněného držitele sociální identity posoudí provozovatel individuálně; automatický převod účtu ani FC není možný. Plánovaný startovní bonus 5 FC pro prvních 1 000 způsobilých creatorů se v pilotu nepřiděluje.'},
    {title:'Zveřejnění a pořadí',text:'Zobrazení profilu v pilotním žebříčku je samostatná volba uživatele, kterou může kdykoli vypnout. Profil se zobrazí jen s alespoň jedním právě aktivním ověřeným sociálním účtem a pokud nebyl omezen moderací. Viditelné jsou zvolené jméno a země, veřejné UUID, odkazy a názvy aktivních ověřených účtů, pořadí a oddělené součty FC a cash USD. E-mail, jednotlivé transakce, přihlašovací údaje a ověřovací tokeny se nezveřejňují. Každý způsobilý creator je v Global žebříčku nejvýše jednou. Pořadí určuje vyšší součet FC a potvrzených hrubých plateb v USD včetně daně; 1 FC má pro výpočet váhu 1 USD. V pilotu je platební složka vždy nula. Při shodě rozhoduje dřívější dosažení stejného součtu, potom veřejné UUID vzestupně. Daily začíná v 00:00 UTC, Weekly v pondělí 00:00 UTC; FC patří do období svého přidělení a zůstávají v All-Time. Žebříček není měřítkem kvality, popularity ani doporučením provozovatele.'},
    {title:'Změny, omezení a ukončení',text:'Provozovatel může přiměřeně měnit funkce pilotu, upravit pravidla nebo pilot ukončit. O podstatné změně pravidel informuje předem na webu nebo e-mailem. Placené funkce ani veřejné zveřejnění profilů se nezačnou používat pouze na základě těchto pravidel. Uživatel může přestat službu používat, skrýt profil a požádat o výmaz. Při porušení pravidel může provozovatel skrýt obsah nebo profil, omezit přístup či účet ukončit; posoudí okolnosti a přiměřenost. Pokud nejde o nutný okamžitý zásah, sdělí důvody a možnost nápravy. Zákonná práva z vadného plnění a na náhradu újmy zůstávají zachována.'},
    {title:'Oznámení obsahu a přezkum',text:'Nezákonný obsah nebo porušení pravidel lze oznámit formulářem /private/report nebo na info@fameriser.com. Uveď přesný odkaz na obsah FameRiseru, konkrétní důvod a vysvětlení, proč jej považuješ za nezákonný nebo odporující pravidlům, své jméno a e-mail a prohlášení, že podání činíš v dobré víře a informace jsou podle tvého vědomí přesné a úplné. Jméno a e-mail nemusíš uvést při oznámení podezření na sexuální zneužívání dětí; takový materiál neposílej jako přílohu. Oznámení posoudí člověk bez svévolného odkladu. O rozhodnutí, jeho důvodech a dostupném přezkumu informujeme oznamovatele, pokud uvedl kontakt, a dotčeného uživatele, pokud to právní předpisy umožňují. Námitku proti omezení nebo rozhodnutí pošli na stejný kontakt.'},
    {title:'Stížnosti a spory',text:'Stížnost na fungování pilotu nebo uplatnění práv pošli na info@fameriser.com; uveď účet, popis problému a požadované řešení. Můžeš se obrátit na příslušný soud. Pokud se na konkrétní spotřebitelský spor vztahuje mimosoudní řešení, příslušným subjektem je Česká obchodní inspekce (coi.gov.cz/informace-o-adr/). V pilotu se neuzavírá placený nákup; budoucí platební podmínky, skutečný prodávající, cena, daně, práva spotřebitele a možnosti odstoupení budou uvedeny před případným nákupem v nových pravidlech a objednávce.'},
  ],
  privacy:[
    {title:'Správce a kontakt',text:'Správcem osobních údajů je Petr Suchý, IČO 87155982, Československé armády 723, Místek, 738 01 Frýdek-Místek, Česká republika. Ve věcech ochrany údajů piš na info@fameriser.com. '},
    {title:'Údaje a jejich zdroj',text:'Od uživatele získáváme e-mail, potvrzení věku a přijetí pravidel, jméno profilu, případně zemi a volbu zveřejnění. Při přihlášení vznikají technické identifikátory účtu, relace a bezpečnostní záznamy. Z Google YouTube API získáváme po tvém ověření identifikátor, název a odkaz kanálu a výsledek ověření. Ukládáme veřejné UUID creatora, propojení účtu, přidělené FC, časové údaje a historii nutnou pro integritu pořadí. Pokud nám napíšeš nebo oznámíš obsah, zpracujeme údaje v podání a související komunikaci. E-mailové pozvánky uchovávají adresu a dobu platnosti. Google přihlašovací ani přístupový token pro YouTube dlouhodobě neukládáme; jednorázový přístupový token použijeme jen během ověření.'},
    {title:'Účely a právní základy',text:'Účet, autentizace, spojení ověřeného sociálního účtu, výpočet skóre a dostupnost služby jsou potřebné k poskytnutí požadovaného pilotu a opírají se o plnění dohody podle čl. 6 odst. 1 písm. b) GDPR. Samostatně zvolený profil zobrazujeme pouze po tvé výslovné publikační volbě v rámci používání služby; volbu lze vypnout. Ochrana proti podvodům a zneužití, správa oznámení obsahu, obhajoba nároků a bezpečnostní záznamy vycházejí z našeho oprávněného zájmu podle čl. 6 odst. 1 písm. f) GDPR na bezpečném a spravedlivém provozu. Plnění zákonných povinností se opírá o čl. 6 odst. 1 písm. c). Marketingové zprávy a nepovinné analytické cookies v tomto pilotu nezapínáme a registrace k nim není souhlasem.'},
    {title:'Co je povinné a kdo co uvidí',text:'E-mail, potvrzení věku, přijetí pravidel a zvolené jméno jsou potřebné k účtu a creator profilu; bez nich nelze službu poskytnout. Země a zveřejnění jsou dobrovolné. Pro účast v žebříčku je třeba alespoň jeden aktivní ověřený sociální účet. V soukromém pilotu uvidí veřejná pole popsaná v části Zveřejnění a pořadí osoby s přístupem k webu. UUID je osobním údajem, pokud lze profil spojit s člověkem. Skrytí profilu brání dalšímu zobrazení v žebříčku, ale nemůže odstranit kopie pořízené dříve jinými osobami. Po odpojení zůstává interně historický identifikátor sociální identity pro zamezení opakovanému přidělení FC a řešení sporů; veřejně se odpojený účet nezobrazuje.'},
    {title:'Příjemci a předávání',text:'Údaje zpracováváme prostřednictvím Supabase (účet, databáze a úložiště), Sites/Cloudflare (hosting, přenos a ochrana provozu) a poskytovatele odchozí autentizační pošty. Při ověření YouTube si údaje vyměňujeme s Googlem podle uživatelem zvoleného oprávnění. Obsah oznámení může být v nutném rozsahu sdělen dotčené osobě, odbornému poradci nebo příslušnému orgánu. Databázový projekt je umístěn v regionu EU; přístup podpory a provozní metadata dodavatelů mohou zahrnovat země mimo EHP. Před spuštěním s účastníky ověříme smlouvy o zpracování a použité záruky pro případná předání podle kapitoly V GDPR; informace a kopii záruk poskytne správce na požádání.'},
    {title:'Doba uchování a výmaz',text:'Účet a creator profil vedeme po dobu používání pilotu. Volba skrytí zastaví další zveřejnění; odpojení účtu ukončí jeho aktivní ověření, ale historické údaje potřebné pro jednorázový FC zůstávají do výmazu profilu. Při žádosti o výmaz ihned skryjeme profil, zablokujeme účet a odstraníme propojení a FC z nového žebříčku; zbývající údaje vyhodnotíme a odstraníme nebo anonymizujeme, jakmile odpadne účel a povinná či obhajitelná retenční doba. Záznamy potřebné pro právní povinnost nebo obhajobu nároků uchováme jen po dobu této povinnosti nebo příslušné promlčecí doby. Pozvánka se smaže po vypršení, záznamy limitů se čistí po 24 hodinách a údaje v záloze až při uplynutí její životnosti. Nevyužité OAuth stavy mají platnost 10 minut a nesmí být po jejím uplynutí použity. Konkrétní provozní lhůty pro dokončení výmazu, zálohy, oznámení obsahu a technické logy zveřejníme po ověření jejich skutečného nastavení, ještě před otevřením pilotu dalším účastníkům.'},
    {title:'Práva a stížnost',text:'Můžeš požádat o přístup, opravu, výmaz, omezení zpracování a v zákonných případech o přenositelnost údajů; proti zpracování z oprávněného zájmu můžeš vznést námitku. Ve svém profilu můžeš vypnout zveřejnění, stáhnout údaje nového profilu a podat žádost o výmaz; o úplný výpis nebo jiná práva požádej na info@fameriser.com. Odpovíme bez zbytečného odkladu, zpravidla do jednoho měsíce; zákon v odůvodněných případech umožňuje prodloužení. Stížnost můžeš podat u Úřadu pro ochranu osobních údajů, uoou.gov.cz.'},
    {title:'Cookies a automatické rozhodování',text:'Používáme technicky nezbytné cookies pro přihlášení a ochranu relace a při propojení YouTube dočasnou OAuth cookie platnou nejvýše 10 minut. Délka přihlašovací relace se řídí nastavením autentizační služby a odhlášením. V novém pilotu nepoužíváme nepovinné analytické ani reklamní cookies. Automatický výpočet pořadí podle zveřejněného vzorce nemá účinek právního nebo obdobně významného automatizovaného rozhodnutí o člověku; rozhodnutí o moderaci přijímá člověk.'},
    {title:'Propojení YouTube',text:'Ověření YouTube využívá Google API Services se čtecím oprávněním youtube.readonly. Údaje z Google použijeme pouze k ověření ovládaného kanálu a zobrazení zvoleného propojení. Propojení můžeš odpojit v profilu a přístup aplikace můžeš kdykoli odvolat v nastavení oprávnění účtu Google na security.google.com/settings/security/permissions. Informace o používání údajů službou Google uvádějí zásady Google. Odpojení samo o sobě nemaže historický záznam FC; o odstranění údajů můžeš požádat podle předchozí části.'},
  ],
} as const;
