import {PRIVATE_RULES_VERSION} from './private-v1';
export const privatePolicy={
  version:PRIVATE_RULES_VERSION,
  sections:[
    {title:'Rozsah soukromého pilotu',text:'FameRiser v této fázi umožňuje vytvořit účet a jeden společný creator profil, připojit ověřené sociální účty a zobrazit pořadí v soukromém pilotním webu. Platby, výběr peněz, výhry a veřejné otevření webu nejsou aktivní. Účet a ověření jsou zdarma. Provozovatel může pilot upravovat nebo ukončit; při ukončení vyřídí existující právní nároky a žádosti o údaje.'},
    {title:'Kdo může účet používat',text:'Účet je určen osobám od 18 let. Pro registraci potřebuješ přístup k potvrzenému e-mailu. K profilu připojuj jen sociální účet, který skutečně ovládáš nebo jsi oprávněn zastupovat. Ověření přístupu není ověřením občanské identity ani kvality obsahu. Zakázáno je vydávání se za jiného, falešná ověření, nelegální obsah a obcházení limitů.'},
    {title:'Jeden profil, ověřené účty',text:'Jeden uživatelský účet má jeden creator profil a tento profil může spojit více ověřených sociálních účtů. Připojení vyžaduje skutečné ověření poskytovatelem podporované sítě; samotný vložený odkaz, screenshot nebo platba nestačí. Stejná sociální identita se nepřevádí automaticky na jiného creatora ani po odpojení. Pokud se její oprávněný vlastník změnil, požádej provozovatele o individuální posouzení převodu a původně přidělených FC. Odpojený účet se přestane zobrazovat a profil bez aktivního ověřeného účtu zmizí ze žebříčku.'},
    {title:'FameCredit a pořadí',text:'Za každý nově připojený odlišný ověřený sociální účet se jednou připíše 1 FameCredit (FC), nejvýše 10 uvítacích FC na creator profil. FC je nepeněžní hodnota pro pořadí: 1 FC má stejnou váhu jako 1 USD uznané platby. FC nelze vyplatit, převést ani použít jako prostředek úhrady. Po odpojení sociálního účtu již přidělené FC zůstávají v All-Time součtu, ale profil se zobrazí pouze tehdy, pokud splňuje podmínky zveřejnění a má alespoň jeden aktivní ověřený účet. Startovní bonus 5 FC pro prvních 1 000 způsobilých creatorů se spustí až při oznámeném oficiálním veřejném startu a v soukromém pilotu se nepřiděluje.'},
    {title:'Výpočet žebříčku',text:'V Global žebříčku je každý způsobilý creator nejvýše jednou. Pořadí určuje vyšší součet uznaných hrubých plateb v USD včetně daně a FC; obě složky se zobrazují samostatně. V soukromém pilotu je platební složka vždy nula. Při shodě je výš creator, který stejného součtu dosáhl dříve; při naprosto shodném čase rozhoduje veřejné UUID v rostoucím pořadí. Daily začíná v 00:00 UTC a Weekly v pondělí 00:00 UTC. FC se v časových žebříčcích počítají jen v období přidělení, v All-Time zůstávají. Pořadí není měřítkem popularity, kvality ani doporučením služby.'},
    {title:'Zveřejnění a odebrání profilu',text:'Zveřejnění v pilotu je volba vlastníka profilu. Zobrazuje se jméno, zvolená země, veřejné UUID, jednotlivé připojené ověřené účty, pořadí a oddělené součty cash USD a FC. E-mail, přihlašovací údaje, poskytovatelské tokeny, důkazy ověření a jednotlivé transakce se nezobrazují. Zveřejnění můžeš vypnout; moderace nebo výmaz profil také skryje. Protože jde o soukromý pilot, profil uvidí osoby s přístupem k pilotnímu webu. Po veřejném spuštění by se rozsah publika změnil; předtím bude vydáno nové upozornění a potřeba nové publikační volby se posoudí samostatně.'},
    {title:'Budoucí platby',text:'Veřejné spuštění plánujeme až po připojení Dodo Payments, ověření platebního toku, vydání platných obchodních informací a dokončení právní kontroly. Jednotlivý budoucí boost má mít minimum 5 USD a bude započten z celé potvrzené hrubé částky včetně daně. Samotné zobrazení plánu v pilotu není nabídkou ke koupi. Checkout před spuštěním ukáže skutečného prodávajícího, cenu, daně, práva spotřebitele a podmínky Dodo.'},
    {title:'Kontakt a žádosti',text:'Dotazy, námitky, oznámení závad, žádosti o přístup nebo výmaz posílej na zveřejněný kontaktní e-mail provozovatele. Odvolání zveřejnění je dostupné v profilu a neomezuje právo na výmaz či jiné zákonné právo. Oznámení nelegálního obsahu posoudí člověk; rozhodnutí o omezení a možnost přezkumu budou sděleny dotčeným osobám.'},
  ],
  privacy:[
    {title:'Správce a účel',text:'Správcem údajů je provozovatel uvedený na této stránce. E-mail a přihlašovací identifikátory slouží k vedení účtu a zabezpečení; údaje creator profilu a ověření slouží k propojení účtů a žebříčku na tvůj pokyn. Právním základem vedení účtu a pilotní služby je plnění smlouvy nebo kroky před jejím uzavřením; bezpečnost a řešení zneužití se opírají o přiměřený oprávněný zájem. Volitelné měření návštěvnosti se provádí pouze po oddělené volbě, pokud je v pilotu zapnuto. Registrace není souhlas s marketingem.'},
    {title:'Kategorie údajů a příjemci',text:'Zpracováváme e-mail a časově omezený seznam e-mailových pozvánek, technické přihlašovací identifikátory, potvrzení věku a přijetí pravidel, zadané jméno a zemi, identifikátor a odkaz ověřeného sociálního účtu, čas a způsob ověření, volbu zveřejnění, granty FC a nezbytné bezpečnostní záznamy. Přihlášení a databázi poskytuje Supabase, hostování a ochranu provozu Sites/Cloudflare. Při propojení YouTube komunikuje prohlížeč a server s Googlem. Přesné smluvní role, poddodavatele a případné předávání mimo EHP musí provozovatel před rozšířením pilotu doložit; region databáze sám o sobě neprokazuje umístění všech provozních metadat.'},
    {title:'Veřejná pole v pilotu',text:'Kdo má přístup k soukromému pilotu, může vidět údaje uvedené výše u zveřejnění profilu. UUID je trvalý veřejný identifikátor profilu a ve spojení s účty je osobním údajem. Cash a FC jsou agregáty, nikoli seznam jednotlivých plateb. Skrytí profilu zamezí dalšímu zobrazení v pilotním žebříčku; nelze zaručit odstranění dříve pořízených kopií u jiných osob.'},
    {title:'Uchování a práva',text:'Účet a profil vedeme po dobu používání služby. Po žádosti o výmaz skryjeme profil a odstraníme údaje, které již nejsou nezbytné; případné nezbytné právní a bezpečnostní záznamy držíme jen po odůvodněnou dobu. Počítadla bezpečnostních limitů jsou navržena k hodinovému úklidu řádků starších 24 hodin a mažou se také při přípravě výmazu účtu. Skutečnou úlohu, ostatní retenční lhůty, zálohy a technický postup musí provozovatel ověřit před provozem s dalšími účastníky. Můžeš požádat o přístup, opravu, výmaz, omezení, přenositelnost tam, kde se uplatní, nebo vznést námitku. Na žádost odpovíme bez zbytečného odkladu v zákonné lhůtě; můžeš se obrátit na ÚOOÚ.'},
    {title:'Cookies',text:'Nezbytné cookies zajišťují přihlášení a bezpečnost. Soukromá nová část FameRiseru nepoužívá volitelné měření žebříčku. Budoucí nepovinné statistiky budou aktivní pouze po samostatném souhlasu. Cookies externích poskytovatelů na jejich doménách se řídí jejich pravidly.'},
  ],
} as const;
