import { Profile } from "./config";
const entries = [
  [
    "Alex Pixel",
    "alex.pixel",
    "Instagram",
    "Creators",
    "Tvořím věci, které stojí za druhý pohled. ✦",
    12500,
  ],
  [
    "Nela Nova",
    "nela.nova",
    "TikTok",
    "Lifestyle",
    "Malé momenty. Velké příběhy. A kafe mezi tím.",
    9300,
  ],
  [
    "Max Level",
    "max.level",
    "YouTube",
    "Gamers",
    "Ještě jeden level. A pak už vážně končím.",
    7800,
  ],
  [
    "Ema Lens",
    "ema.lens",
    "Instagram",
    "Photography",
    "Svět skrz objektiv. Praha a všechno za ní.",
    6100,
  ],
  [
    "Oliver Beat",
    "oliver.beat",
    "YouTube",
    "Music",
    "Zvuk pro tvoje pozdní večery.",
    4900,
  ],
  [
    "Sofie Studio",
    "sofie.studio",
    "Instagram",
    "Artists",
    "Trochu designu. Trochu chaosu. Hodně barev.",
    3500,
  ],
  [
    "Maty Code",
    "maty.code",
    "YouTube",
    "Developers",
    "Stavím malé produkty s velkými ambicemi.",
    2700,
  ],
  [
    "Viki Move",
    "viki.move",
    "TikTok",
    "Fitness",
    "Pohyb, který tě baví. Každý den o kousek dál.",
    2200,
  ],
  [
    "Leo Live",
    "leo.live",
    "Twitch",
    "Streamers",
    "Živě, bez filtru. Přidej se do chatu.",
    1900,
  ],
  [
    "Anna Frame",
    "anna.frame",
    "Instagram",
    "Photography",
    "Sbírám světlo a příběhy z cest.",
    1500,
  ],
  [
    "Theo Works",
    "theo.works",
    "Facebook",
    "Business",
    "Nápady měním na malé fungující firmy.",
    1200,
  ],
  [
    "Mia Bloom",
    "mia.bloom",
    "Instagram",
    "Lifestyle",
    "Každodennost trochu jinak.",
    1000,
  ],
  [
    "Sam Quest",
    "sam.quest",
    "YouTube",
    "Gamers",
    "Dobrodružství začíná tam, kde končí návod.",
    850,
  ],
  [
    "Eli Craft",
    "eli.craft",
    "Facebook",
    "Artists",
    "Vytvořeno rukama. A s velkou trpělivostí.",
    700,
  ],
  [
    "Dan Wave",
    "dan.wave",
    "Instagram",
    "Creators",
    "Dobré vlny a ještě lepší záběry.",
    600,
  ],
  [
    "Luna Pop",
    "luna.pop",
    "TikTok",
    "Comedy",
    "Dneska se bereme o trochu méně vážně.",
    500,
  ],
  [
    "Ben Loop",
    "ben.loop",
    "Twitch",
    "Streamers",
    "Jeden stream, tisíc příběhů.",
    400,
  ],
  [
    "Zoe Spark",
    "zoe.spark",
    "Instagram",
    "Influencers",
    "Záblesky z mého malého vesmíru.",
    300,
  ],
  [
    "Felix Forum",
    "felix.forum",
    "Facebook",
    "Other",
    "Zvědavost je moje superschopnost.",
    200,
  ],
  [
    "Ada Ideas",
    "ada.ideas",
    "Facebook",
    "Business",
    "Propojuji dobré nápady s dobrými lidmi.",
    100,
  ],
] as const;
export const demoProfiles: Profile[] = entries.map(
  ([name, username, platform, category, bio, paid], i) => ({
    id: `demo-${i + 1}`,
    name,
    username,
    slug: username.replace(".", "-"),
    bio,
    language: i % 4 === 1 ? "sk" : i % 4 === 3 ? "en" : "cs",
    country: i % 4 === 1 ? "SK" : i % 4 === 3 ? "GB" : "CZ",
    region: i % 4 === 1 ? "Bratislavský kraj" : i % 4 === 3 ? "Londýn" : i % 3 ? "Jihomoravský kraj" : "Praha",
    platform,
    category,
    social_url: `https://example.com/${username}`,
    total_paid: paid * 100,
    avatar_url: null,
    reached_amount_at: new Date(Date.UTC(2026, 8, 10, 8, i)).toISOString(),
    created_at: new Date(Date.UTC(2026, 8, 1 + (i % 10))).toISOString(),
    status: "active",
    verified: false,
    views: 0,
    clicks: 0,
    today_paid: [
      150000, 230000, 80000, 0, 90000, 0, 70000, 0, 40000, 0, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 0,
    ][i],
    week_paid: Math.round(paid * 100 * (i % 3 === 0 ? .7 : .35)),
    month_paid: Math.round(paid * 100 * .9),
    demo: true,
  }),
);
